- name: user for jenkins
  include_role:
    name: user
  vars:
    user_name: "{{ jenkins_user | default('jenkins') }}"
    user_group: "{{ jenkins_user | default('jenkins') }}"
  when: ansible_local.jenkins is undefined or not ansible_local.jenkins.USER_INIT

- name: dir
  become: yes
  file:
    name: "{{ item }}"
    state: directory
    owner: "{{ jenkins_user | default('jenkins') }}"
    group: "{{ jenkins_user| default('jenkins') }}"
    recurse: yes
  loop:
    - "{{ jenkins_home }}"
    - "{{ jenkins_war }}"
    - "{{ jenkins_config }}"

- name: download
  become: yes
  get_url:
    url: "{{ jenkins_link }}"
    dest: "{{ jenkins_war | default('/usr/share/jenkins') }}"
    owner: "{{ jenkins_user | default('jenkins') }}"
    group: "{{ jenkins_user| default('jenkins') }}"
    mode: 0755

- name: copy templates
  become: yes
  template: src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
  loop:
    - { src: jenkins,
        dest: "{{ jenkins_config }}",
        owner: "{{ jenkins_user | default('jenkins') }}",
        group: "{{ jenkins_user | default('jenkins') }}",
        mode: "0644" }
    - { src: jenkins.service,
        dest: "{{ sysd }}/jenkins.service",
        owner: root,
        group: root,
        mode: "0644" }
  notify:
    - jenkins_start
    - jenkins_fact

- name: jenkins_port_fact
  set_fact:
     jenkins_port: "{{ jenkins_port }}"

- name: running
  become: yes
  systemd:
    name: jenkins.service
    state: started
    enabled: yes
  notify:
    - jenkins_start
